import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./navbar/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen overflow-x-hidden">
        <Navbar />
        {/* {children} */}
        <main className="container w-100vw bg-[#FEFCFB] mx-auto ">
          {children}
        </main>
      </body>
    </html>
  );
}
